### ISSUE TITLE
GetReturnAddress from detour types

### ISSUE THREAD

**Issue by Maktm** [RaptorFactor/hadesmem#3]
So when trying to get the return address from inside of a hook (for logging purposes) I noticed that the return address returned is the one for the generated code by hadesmem. This is a suggestion to add a GetReturnAddress into hadesmem::PatchDetourBase.

**Comment by RaptorFactor** [comment]
Yep I can definitely understand the use case for this. Good idea.

**Comment by RaptorFactor** [comment]
Resolved @ d4d41d256ee3b51c6f2f49ba05b2ee3053d0788d. Thanks Maktm for providing the implementation.
