### ISSUE TITLE
Attempt at implementing GetReturnAddress

### ISSUE THREAD

**Issue by Maktm** [RaptorFactor/hadesmem#5]
Here's an implementation of GetReturnAddress I put together. This issue is mainly to serve as some notes for me if I get the time to implement the whole thing and a heads up for anyone interested in this issue (https://github.com/RaptorFactor/hadesmem/issues/3). Since it's nowhere near a finished state I didn't create a pull request (or even commit it to my fork). The implementation works in the same way that GetOriginalArbitraryUserPtrPtr works.

First I implemented a copy of GetOriginalArbitraryUserPtrPtr but for the getting the return address from within a hook:

https://gist.github.com/maktm/3504e56f1c45bd302dcc39f62891a309

Then I modified the code for stub generation and modified it to this:

https://gist.github.com/maktm/767f776ecbf137719d14cdd4132c9b60
https://gist.github.com/maktm/4c04378d7869e2b088fe28f55ae7772d

Obviously some modifications were made to the code that calls these modified functions but very few changes were required to get this working.

Usage:

https://gist.github.com/maktm/5ab8cd2ba5095765dcf09d3858ea01b6

Oh and @RaptorFactor what are the meanings of the numbers in this sum:

```
std::size_t const kStubPtrOfs = 9 + 5;
std::size_t const kUserPtrOfs = 20 + 5;
```

Inside of the modified code I just added constants.
## 

I should've replied in the original issue. Any chance you can move it?

**Comment by Maktm** [comment]
Alright so I think I've managed to create a working solution for this that supports both x86 and x64. I can't seem to see any errors at this point in time but point out any if you do:

https://gist.github.com/Maktm/a9803cb8bc57a305c77a4360d936c636

I'd commit this to my fork and open a pull request but my fork is full of commits and isn't aligned with the master hadesmem branch (plus I suck at git).

**Comment by RaptorFactor** [comment]
Hey, thanks for this! I'll give this an in-depth review over the next couple of days, but at first glance it looks correct. The main tricky part is making sure the assembly stubs don't mess up the contents of any registers on its way to actually calling the target, but it looks like you got that figured out.  :)

P.S. No idea how to merge this with the other issue (I also suck at git). No biggie though.

**Comment by RaptorFactor** [comment]
LGTM. I'll do a merge and test tonight, but I don't see anything signalling problems.

**Comment by RaptorFactor** [comment]
Merged fine with some tweaks. Doing testing now.

**Comment by Maktm** [comment]
@RaptorFactor You might want to consider changing PatchDetourBase::GetReturnAddress so that it's not a pure virtual function. That way all the detour types don't have to implement it in order to be instantiated.  Defining it as a virtual method with an assert (e.g. "This feature is not supported") and overriding it inside of PatchDetour should work.

**Comment by RaptorFactor** [comment]
@Maktm GetReturnAddressPtr isn't pure virtual in what you pasted I thought? The tweaks needed while merging were for WriteStubGate calls in each of the derived types because they needed the extra function pointer. I guess I guess I could pass nullptr there and update the codegen to omit the return address stuff,  and then override the virtual like you say to disable the functionality. However, I'm actually wondering now if it wouldn't work on some of the others anyway.

**Comment by Maktm** [comment]
Oh, I was thinking of an old implementation and forgot the one I posted. Sorry about that.

> However, I'm actually wondering now if it wouldn't work on some of the others anyway.

Yeah not too sure about that either. I guess we'll have to see in the future :)

**Comment by RaptorFactor** [comment]
Sorry for delay. Family stuff. Haven't dropped this. Just have a lot going on atm.

**Comment by RaptorFactor** [comment]
Sorry for the delay, I'm finally back. Merged.
