### ISSUE TITLE
Disabling pugixml dependency by default

### ISSUE THREAD

**Issue by Maktm** [RaptorFactor/hadesmem#9]
Findpattern depends on pugixml by default even when the user isn't using any of the classes/methods that use pugixml which increases work for the common user (e.g. me). If you deem it a good idea you can do the same thing I did here:

https://github.com/Maktm/hadesmem/commit/a85aabe5f88a76ebc513fc805986c0efc19a9405

The macro sort of sucks.

**Comment by RaptorFactor** [comment]
In order to not break existing clients I've inverted the macro (HADESMEM_NO_PUGIXML) similar to what Boost does. Hence the default will unfortunately be 'on', but hopefully this is a sufficient compromise? Feel free to argue, I'm open to options, just being cautious for now.

**Comment by Maktm** [comment]
Nope, that looks great. Will test it out after i reset my fork.

**Comment by Maktm** [comment]
Yep, works. Thankss
